version: '3.7'

services:
  postgres:
    image: ankane/pgvector:latest  # imagem com pgvector jรก incluso
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ia
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
